services:
  - type: web
    name: crushconnect-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        value: "@AAUCrushConnect"
      - key: ADMIN_GROUP_ID
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
